= Primera Tarea - Tercera Entrega = 

== Resumen ==

*Materia:* CI-0124 Computabilidad y Complejidad

*Profesora:* Prof. Maureen Murillo R.

*Asistente:*

*Grupo:* FrescoLecheEnSalsa

*Autores:* Joseph Valverde, Kenneth Villalobos, Alejandro Jimenez

*Descripción:* Herramienta tal, que a partir de un archivo XML con información de visitas a sitios de Internet, pueda realizar un análisis para verificar si la sintaxis está correcta y en caso contrario, imprime el error.

== Requerimientos ==

Crear una herramienta tal, que a partir de un archivo XML con información de visitas a sitios de Internet, pueda realizar un análisis para verificar si la sintaxis está correcta y en caso contrario, imprime el error.

No se deben crear objetos o estructuras de datos dinamicamente en esta entrega.

== Solución ==

=== Analizado lexico ===

Se utlizó la biblioteca ply de python, con la cual, se definieron tanto tokens como reglas de gramática. Posteriormente, se crearon tanto el lexer como el parser. Finalmente se leyó el XML disponible, se extrayeron los tokens por medio del lexer y se verificarón las reglas de gramática usando dichos tokens por medio del parser.

=== Paquetes incluidos ===

`import ply.lex as lex`

Para el analisis lexico con la utilización de expresiones regulares y tokens.

`import ply.yacc as yacc`

Para el analisis sintáctico con la utilización de reglas de gramática.

`from pathlib import Path`

Para el uso de "paths" absolutos y facilitar el uso del archivo de entrada, independientemente de su localización en el sistema. 

== Manual de Uso ==

=== Archivo de datos a analizar ===

Para utilizar este programa, se necesita la presencia de un archivo xml en la misma carpeta que el ejecutable con el nombre `python lexsynanalyzer.py`

=== Generar output en terminal ===

Hay varias maneras de correr el programa en la linea de comando. Dentro de las que se utilizan son: 

- `python lexsynanalyzer.py`
- `python3 lexsynanalyzer.py`

Cual comando sea necesario pueda depender del sistema, y ambos pueden, una vez mas, dependiendo del sistema, ser validos en el mismo sistema.

=== Generar output en un archivo de texto ===

El siguiente comando genera un archivo de texto llamado `output.txt` con el output producido. Sin embargo, se le recomienda no utilizarlo puesto que la salida en terminal de este programa es extremadamente reducida y la mayoría de información ya será generada en un archivo .out independientemente.

- `python lexsynanalyzer.py > output.txt` 

El comando de python, una vez mas, depende del sistema, tal como en la seccion pasada de generar output en terminal.


=== Posibles errores ===

De darse un documento con formato XML, pero cuyo contenido no esté en este, la lectura del mismo no generará la salida esperada. 

== Creditos ==

=== Diseñado e impletado por: ===

Joseph Stuart Valverde Kong, C18100

Estudiante de Computación en varios Énfasis en La Universidad de Costa Rica 

*Email:* joseph.valverdekong@ucr.ac.cr

Kenneth Daniel Villalobos Solís, C18548

Estudiante de Computación en varios Énfasis en La Universidad de Costa Rica

*Email:* kenneth.villalobossolis@ucr.ac.cr

Alejandro Jiménez Corea, B84032

Estudiante de Computación en varios Énfasis en La Universidad de Costa Rica

*Email:* alejandro.jimenezcorea@ucr.ac.cr

=== Fuentes ===

Reading a file using a relative path in a Python project (Stack Overflow)

*Encontrado en:* https://stackoverflow.com/questions/40416072/reading-a-file-using-a-relative-path-in-a-python-project 


=== Codigo Original/Base ===

Prof. Maureen Murillo R.
