
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOSE_TAG_DATA CLOSE_TAG_FINAL_DATE CLOSE_TAG_INITIAL_DATE CLOSE_TAG_NUMBER_OF_VISITS CLOSE_TAG_RECORD CLOSE_TAG_RECORDS CLOSE_TAG_REGION CLOSE_TAG_REGIONS CLOSE_TAG_SITE CLOSE_TAG_SITES CLOSE_TAG_TITLE CLOSE_TAG_TOPIC CLOSE_TAG_TOPICS CLOSE_TAG_URL DATE LINK NUMBER OPEN_TAG_DATA OPEN_TAG_FINAL_DATE OPEN_TAG_INITIAL_DATE OPEN_TAG_NUMBER_OF_VISITS OPEN_TAG_RECORD OPEN_TAG_RECORDS OPEN_TAG_REGION OPEN_TAG_REGIONS OPEN_TAG_SITE OPEN_TAG_SITES OPEN_TAG_TITLE OPEN_TAG_TOPIC OPEN_TAG_TOPICS OPEN_TAG_URL TEXTstart : OPEN_TAG_DATA topics regions sites CLOSE_TAG_DATAtopics : OPEN_TAG_TOPICS topics_list CLOSE_TAG_TOPICSregions : OPEN_TAG_REGIONS regions_list CLOSE_TAG_REGIONSsites : OPEN_TAG_SITES sites_list CLOSE_TAG_SITESrecords : OPEN_TAG_RECORDS records_list CLOSE_TAG_RECORDStopics_list : TOPIC topics_list\n                 | TOPICregions_list : REGION regions_list\n                  | REGIONsites_list : SITE sites_list\n                | SITErecords_list : RECORD records_list\n                  | RECORDTOPIC : OPEN_TAG_TOPIC TEXT CLOSE_TAG_TOPICREGION : OPEN_TAG_REGION TEXT CLOSE_TAG_REGIONSITE : OPEN_TAG_SITE URL TITLE topics records CLOSE_TAG_SITERECORD : OPEN_TAG_RECORD INITIAL_DATE FINAL_DATE REGION VISITS CLOSE_TAG_RECORDURL : OPEN_TAG_URL LINK CLOSE_TAG_URLTITLE : OPEN_TAG_TITLE TEXT CLOSE_TAG_TITLEINITIAL_DATE : OPEN_TAG_INITIAL_DATE DATE CLOSE_TAG_INITIAL_DATEFINAL_DATE : OPEN_TAG_FINAL_DATE DATE CLOSE_TAG_FINAL_DATEVISITS : OPEN_TAG_NUMBER_OF_VISITS NUMBER CLOSE_TAG_NUMBER_OF_VISITS'
    
_lr_action_items = {'OPEN_TAG_DATA':([0,],[2,]),'$end':([1,18,],[0,-1,]),'OPEN_TAG_TOPICS':([2,31,39,],[4,4,-19,]),'OPEN_TAG_REGIONS':([3,15,],[6,-2,]),'OPEN_TAG_TOPIC':([4,8,25,],[9,9,-14,]),'OPEN_TAG_SITES':([5,22,],[11,-3,]),'OPEN_TAG_REGION':([6,13,30,48,56,],[14,14,-15,14,-21,]),'CLOSE_TAG_TOPICS':([7,8,16,25,],[15,-7,-6,-14,]),'TEXT':([9,14,32,],[17,24,35,]),'CLOSE_TAG_DATA':([10,26,],[18,-4,]),'OPEN_TAG_SITE':([11,20,40,],[21,21,-16,]),'CLOSE_TAG_REGIONS':([12,13,23,30,],[22,-9,-8,-15,]),'OPEN_TAG_RECORDS':([15,34,],[-2,38,]),'CLOSE_TAG_TOPIC':([17,],[25,]),'CLOSE_TAG_SITES':([19,20,27,40,],[26,-11,-10,-16,]),'OPEN_TAG_URL':([21,],[29,]),'CLOSE_TAG_REGION':([24,],[30,]),'OPEN_TAG_TITLE':([28,36,],[32,-18,]),'LINK':([29,],[33,]),'OPEN_TAG_NUMBER_OF_VISITS':([30,51,],[-15,55,]),'CLOSE_TAG_URL':([33,],[36,]),'CLOSE_TAG_TITLE':([35,],[39,]),'CLOSE_TAG_SITE':([37,44,],[40,-5,]),'OPEN_TAG_RECORD':([38,42,57,],[43,43,-17,]),'CLOSE_TAG_RECORDS':([41,42,45,57,],[44,-13,-12,-17,]),'OPEN_TAG_INITIAL_DATE':([43,],[47,]),'OPEN_TAG_FINAL_DATE':([46,53,],[49,-20,]),'DATE':([47,49,],[50,52,]),'CLOSE_TAG_INITIAL_DATE':([50,],[53,]),'CLOSE_TAG_FINAL_DATE':([52,],[56,]),'CLOSE_TAG_RECORD':([54,59,],[57,-22,]),'NUMBER':([55,],[58,]),'CLOSE_TAG_NUMBER_OF_VISITS':([58,],[59,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'topics':([2,31,],[3,34,]),'regions':([3,],[5,]),'topics_list':([4,8,],[7,16,]),'TOPIC':([4,8,],[8,8,]),'sites':([5,],[10,]),'regions_list':([6,13,],[12,23,]),'REGION':([6,13,48,],[13,13,51,]),'sites_list':([11,20,],[19,27,]),'SITE':([11,20,],[20,20,]),'URL':([21,],[28,]),'TITLE':([28,],[31,]),'records':([34,],[37,]),'records_list':([38,42,],[41,45,]),'RECORD':([38,42,],[42,42,]),'INITIAL_DATE':([43,],[46,]),'FINAL_DATE':([46,],[48,]),'VISITS':([51,],[54,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> OPEN_TAG_DATA topics regions sites CLOSE_TAG_DATA','start',5,'p_start','main.py',210),
  ('topics -> OPEN_TAG_TOPICS topics_list CLOSE_TAG_TOPICS','topics',3,'p_topics','main.py',215),
  ('regions -> OPEN_TAG_REGIONS regions_list CLOSE_TAG_REGIONS','regions',3,'p_regions','main.py',224),
  ('sites -> OPEN_TAG_SITES sites_list CLOSE_TAG_SITES','sites',3,'p_sites','main.py',228),
  ('records -> OPEN_TAG_RECORDS records_list CLOSE_TAG_RECORDS','records',3,'p_records','main.py',232),
  ('topics_list -> TOPIC topics_list','topics_list',2,'p_topics_list','main.py',242),
  ('topics_list -> TOPIC','topics_list',1,'p_topics_list','main.py',243),
  ('regions_list -> REGION regions_list','regions_list',2,'p_regions_list','main.py',247),
  ('regions_list -> REGION','regions_list',1,'p_regions_list','main.py',248),
  ('sites_list -> SITE sites_list','sites_list',2,'p_sites_list','main.py',254),
  ('sites_list -> SITE','sites_list',1,'p_sites_list','main.py',255),
  ('records_list -> RECORD records_list','records_list',2,'p_records_list','main.py',259),
  ('records_list -> RECORD','records_list',1,'p_records_list','main.py',260),
  ('TOPIC -> OPEN_TAG_TOPIC TEXT CLOSE_TAG_TOPIC','TOPIC',3,'p_topic','main.py',265),
  ('REGION -> OPEN_TAG_REGION TEXT CLOSE_TAG_REGION','REGION',3,'p_region','main.py',274),
  ('SITE -> OPEN_TAG_SITE URL TITLE topics records CLOSE_TAG_SITE','SITE',6,'p_site','main.py',280),
  ('RECORD -> OPEN_TAG_RECORD INITIAL_DATE FINAL_DATE REGION VISITS CLOSE_TAG_RECORD','RECORD',6,'p_RECORD','main.py',429),
  ('URL -> OPEN_TAG_URL LINK CLOSE_TAG_URL','URL',3,'p_URL','main.py',449),
  ('TITLE -> OPEN_TAG_TITLE TEXT CLOSE_TAG_TITLE','TITLE',3,'p_TITLE','main.py',455),
  ('INITIAL_DATE -> OPEN_TAG_INITIAL_DATE DATE CLOSE_TAG_INITIAL_DATE','INITIAL_DATE',3,'p_INITIAL_DATE','main.py',461),
  ('FINAL_DATE -> OPEN_TAG_FINAL_DATE DATE CLOSE_TAG_FINAL_DATE','FINAL_DATE',3,'p_FINAL_DATE','main.py',467),
  ('VISITS -> OPEN_TAG_NUMBER_OF_VISITS NUMBER CLOSE_TAG_NUMBER_OF_VISITS','VISITS',3,'p_VISITS','main.py',473),
]
