= Primera Tarea = 

== Resumen ==

*Materia:* CI-0124 Computabilidad y Complejidad

*Profesora:* Prof. Maureen Murillo R.

*Asistente:*

*Grupo:* FrescoLecheEnSalsa

*Autores:* Joseph Valverde, Kenneth Villalobos, Alejandro Jimenez

*Descripción:* Herramienta tal, que a partir de un archivo XML con información de visitas a sitios de Internet su aplicación pueda generar algunas estadísticas interesantes sobre el interés de la gente por temas particulares.

== Requerimientos ==

Crear una gerramienta tal, que a partir de un archivo XML con información de visitas a sitios de Internet su aplicación pueda generar algunas estadísticas interesantes sobre el interés de la gente por temas particulares.

De estos, las estadistias a generar son:

1. Listado de sitios disponibles por tema (Se listaran todos los temas como títulos y justo debajo de cada uno, cada sitio que utiliza este tema como subtítulo)

2. Comparación del número de visitas por sitio, por año (Se mostrará una serie de años disponibles para elegir a partir de los datos recopilados, el usuario seleccionará uno y se le mostrará un gráfico de barras con el número de visitas en ese año como eje y, y los sitios como eje x).

3. Comparación del número de visitas por tema, por año (Se mostrará una serie de años disponibles para elegir a partir de los datos recopilados, el usuario seleccionará uno y se le mostrará un gráfico de barras con el número de visitas en ese año como eje y, y los temas como eje x).

4. Comparación de visitas por país, por año (Se mostrará una serie de años disponibles para elegir a partir de los datos recopilados, el usuario seleccionará uno y se le mostrará un gráfico de barras con el número de visitas en ese año como eje y, y los países como eje x).


== Solucion ==

=== Analizado lexico ===

Se utliza la biblioteca ply de python, con la cual, a traves del uso de expresiones regulares, se definieron tokens, las cuales son leidas, identificadas y extraidas.  

=== Estructuras a utilizar ===

1. Arreglo de listas de sitios (strings) 
2. Mapa que asocia años (ints) con mapas que asocian sitios (strings) con números de visitas (ints)
3. Mapa que asocia años (ints) con mapas que asocian temas (strings) con números de visitas (ints)
4. Mapa que asocia años (ints) con mapas que asocian países (strings) con números de visitas (ints)

=== Paquetes incluidos ===

`import ply.lex as lex`

Para el analisis lexico con la utilización de expresiones regulares y tokens

`from pathlib import Path`

Para el uso de "paths" absolutos y facilitar el uso del documento, independientement de su localización en el sistema. 

== Manual de Uso ==

=== Documento de datos a analizar ===

Para utilizar este programa, se necesita la presencia de un documento xml en la misma carpeta que el ejecutable con el nombre `data.xml`

=== Con output en terminal ===

Hay varias maneras de correr el programa en la linea de comando. Dentro de las que se utilizan son: 

- `python lexanalyzer.py`
- `python3 lexanalyzer.py`

Cual comando sea necesario pueda depender del sistema, y ambos pueden, una vez mas, dependiendo del sistema, ser validos en el mismo sistema.

=== Con output generado escrito a documento ===

El siguiente documento genera un documento con el output llamado `output.txt`

- `python lexanalyzer.py > output.txt` 

El comando de python, una vez mas, depende del sistema, tal como en la seccion pasada de output en el terminal.


=== Posibles errores ===

Es posible que de darse el nombre de un sitio, como un url, este sea identificado como url, en lugar del nombre de un sitio. El comportamiento para este tipo de encuentros, esta aún por definir.

De darse un documento con formato XML, pero cuyo contenido no esté en este, la lectura de este no va a generar la salida esperada. 

== Creditos ==

=== Diseñado e impletado por: ===

Joseph Stuart Valverde Kong, C18100

Estudiante de Computación en varios Énfasis en La Universidad de Costa Rica 

*Email:* joseph.valverdekong@ucr.ac.cr

Kenneth Daniel Villalobos Solís, C18548

Estudiante de Computación en varios Énfasis en La Universidad de Costa Rica

*Email:* kenneth.villalobossolis@ucr.ac.cr

Alejandro Jimenez,

Estudiante de Computación en varios Énfasis en La Universidad de Costa Rica

*Email:*

=== Fuentes ===

Reading a file using a relative path in a Python project (Stack Overflow)

*Encontrado en:* https://stackoverflow.com/questions/40416072/reading-a-file-using-a-relative-path-in-a-python-project 


=== Codigo Original/Base ===

Prof. Maureen Murillo R.
